version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            /root/.pyenv/versions/3.6.9/bin/python -mvenv /usr/local/share/virtualenvs/tap-dayforce
            source /usr/local/share/virtualenvs/tap-dayforce/bin/activate
            pip install -U 'pip<19.2' setuptools
            pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-dayforce/bin/activate
            make test
